name: Build Frontend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd app/fe
          npm install

      - name: Build
        run: |
          cd app/fe
          npm run build

      - name: Copy build to fe folder
        run: |
          rm -rf fe
          mkdir fe
          cp -r app/fe/dist/* fe/

      - name: Commit build
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add fe
          git commit -m "Auto build frontend" || echo "No changes"
          git push